---
sources:
    - name: meter_source
      meters:
          - "*"
      sinks:
          - meter_file
sinks:
    - name: meter_file 
      meters:
          - "*"
      publishers:
          - file:///var/test/ceiltest?max_bytes=10000000&backup_count=5&json
            #- file:///home/controller/test?max_bytes=10000000&backup_count=5&json
            #- file:///var/test22.log
